public with sharing class IntegrationLogConstants {

    public static final String DIRECTION_OUTBOUND = 'Outbound';
    public static final String DIRECTION_INBOUND = 'Inbound';

    public static final String STATUS_SUCCESS = 'Success';
    public static final String STATUS_ERROR = 'Error';
    public static final String STATUS_PENDING = 'Pending';
    public static final String STATUS_IGNORED = 'Ignored';

    public static final String HUB_SALESFORCE = 'Hub Salesforce';
}
